### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Wildhoney** [samrat/jopbox#8]
I'm fairly new to Clojure, so apologies for any ignorance.

I've tried to setup using the instructions, however as soon as I add the `fetch-request-token` line I receive a `java.lang.NullPointerException`:

``` clojure
(ns server.handler
  (:require [compojure.core :refer :all]
            [compojure.route :as route]
            [ring.middleware.defaults :refer [wrap-defaults site-defaults]]
            [jopbox.client :refer :all]))

(def app-key (System/getenv "DROPBOX_APP_KEY"))
(def app-secret (System/getenv "DROPBOX_APP_SECRET"))

(def consumer (make-consumer app-key app-secret))
(def request-token (fetch-request-token consumer))
```

I referred to your tests and saw that you didn't supply `callback-url`, so I tried that myself, but even when I do specify a `callback-url` the result is the same. Ideally I don't want to specify one, as this is authenticating with the same user every time to retrieve pictures.

Do you have any idea what I might be doing wrong? And is it okay to not pass a `callback-url`? In the [other](https://github.com/aria42/clj-dropbox) Dropbox API for Clojure they mentioned you can pass `nil` as the `callback-url`, which seems to be what I'm after.

![Screenshot](http://i.imgur.com/O6ShhSO.png)

**Comment by Wildhoney** [comment]
From looking at the source of `fetch-request-token` it seems `nil` is acceptable, which answers my own question. However even in the REPL I still get the error thrown.

```
user=> (def request-token (fetch-request-token consumer))

CompilerException java.lang.NullPointerException, compiling:(form-init7199803185078220184.clj:1:20) 
```

**Comment by samrat** [comment]
Hi @Wildhoney , I am unable to reproduce this problem. Could you paste what `consumer` is set to for you? Make sure you remove your API key and secret before sharing it here. I am suspecting that `consumer` did not get properly defined for you.

**Comment by Wildhoney** [comment]
@sam I've just tried it now in the REPL, and everything seems to be working perfectly. Hmm. I'm almost sure these are the exact steps I was taking the other day. Maybe the Dropbox API had some downtime? I'm not sure. How would it handle failures? Thanks nonetheless!

``` bash
user=> (def consumer (make-consumer (System/getenv "DROPBOX_APP_KEY") (System/getenv "DROPBOX_APP_SECRET")))
#'user/consumer
user=> consumer
#oauth.client.Consumer{:key "x", :secret "x", :request-uri "https://api.dropbox.com/1/oauth/request_token", :access-uri "https://api.dropbox.com/1/oauth/access_token", :authorize-uri "https://www.dropbox.com/1/oauth/authorize", :signature-method :hmac-sha1}
user=> (def request-token (fetch-request-token consumer))
#'user/request-token
```
